sonar.projectKey=TON_NOM_D_UTILISATEUR_PROJET
sonar.organization=TON_ORGANISATION_SONAR
sonar.projectName=AuthServerTP5
sonar.projectVersion=1.0

# Chemin vers les sources
sonar.sources=./src
# Exclure les tests de l'analyse de code source
sonar.tests=./__test__
# Encodage
sonar.sourceEncoding=UTF-8
# Langage spécifique (Node.js est détecté automatiquement)